name: Bundle/Release idTip_CommunityFork.zip

on:
  push:
    branches:
      - main

jobs:
  Bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/checkout@v1
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: "${{ github.token }}"
      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "{{IDTIP_VERSION}}"
          replace: ${{ steps.semvers.outputs.patch }}
          regex: false
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v3.0.0
        with:
          myToken: ${{ github.token }}
      - name: Make idTip_CommunityFork directory
        run: mkdir idTip_CommunityFork
      - name: Move all files to idTip_CommunityFork directory
        run: mv *.toc idTip_CommunityFork/ && mv clients/ idTip_CommunityFork/ && mv core/ idTip_CommunityFork/ && mv libs/ idTip_CommunityFork/
      - name: Zip idTip_CommunityFork
        uses: montudor/action-zip@v1.0.0
        with:
          args: zip -qq -r idTip_CommunityFork-${{ steps.semvers.outputs.patch }}.zip idTip_CommunityFork
      - name: Upload Release Package
        uses: actions/upload-artifact@v2
        with:
          name: idTip_CommunityFork
          path: idTip_CommunityFork
      - name: release
        uses: ncipollo/release-action@v1.11.1
        id: create_release
        with:
          tag: ${{ steps.semvers.outputs.patch }}
          name: idTip_CommunityFork v${{ steps.semvers.outputs.patch }}
          body: ${{ steps.changelog.outputs.changelog }}
          artifacts: "idTip_CommunityFork-${{ steps.semvers.outputs.patch }}.zip"
        env:
          GITHUB_TOKEN: ${{ github.token }}
